server:
  port: 8080
spring:
  application:
    name: SpringSecurityStudy
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/edu
    username: root
    password: 1234
